[project]
name = "resturant"

[[services]]
name = "web"
port = 5000
build = """
# Upgrade pip and install Python dependencies
python -m pip install --upgrade pip
python -m pip install -r requirements.txt

# Install Bun packages and build React frontend
bun install
bun build src/frontend.tsx --outdir=static/assets --minify

# Build Tailwind CSS
npx tailwindcss -i ./static/css/tailwind.css -o ./static/css/tw.css --minify
"""
start = "python app.py"
